name: Unit Testing

on: push

jobs:
    test:
        runs-on: ubuntu-latest
        env:
            DB_DATABASE: ontrack
            DB_USER: root
            DB_PASSWORD: "root"
            DB_HOST: localhost
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pillow
                  pip install pytest
                  pip install mysql-connector-python
            - name: MySQL set up
              run: |
                  sudo /etc/init.d/mysql start
                  mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }}; USE ${{ env.DB_DATABASE }}; SOURCE src/database/ontrack.sql;' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
            - name: Unit testing
              run: pytest -o log_cli=true
